apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocfcloud.resourcedirectory.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ocfcloud.resourcedirectory.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.services.resourcedirectory.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "ocfcloud.resourcedirectory.selectorLabels" . | nindent 4 }}
